import type { Metadata } from "next";
import { Inter, Poppins, Volkhov } from "next/font/google";
import "./styles/globals.scss";

const inter = Inter({
  style: ["normal"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--font-inter",
});

const poppins = Poppins({
  style: ["normal", "italic"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
  subsets: ["latin"],
});

const volkhov = Volkhov({
  style: ["normal", "italic"],
  weight: ["400", "700"],
  variable: "--font-volkhov",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${poppins.variable} ${volkhov.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
