version: "3.8"

services:
  postgres:
    container_name: postgres-hotel-booking-api
    image: postgres
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data